name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

jobs:

  pub-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.5
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run publish dry run
        run: dart pub publish --dry-run

  release:
    name: Release
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.5
    timeout-minutes: 20
    #env:
      #PUB_DEV_CREDENTIAL: ${{ secrets.PUB_DEV_CREDENTIAL }}
      #PUB_DEV_REFRESH_TOKEN: ${{ secrets.PUB_DEV_REFRESH_TOKEN }}
      #PUB_DEV_ID_TOKEN: ${{ secrets.PUB_DEV_ID_TOKEN }}
      #PUB_DEV_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_TOKEN_ENDPOINT }}
      #PUB_DEV_EXPIRATION: ${{ secrets.PUB_DEV_EXPIRATION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: flutter pub get
      - name: Write to Pub dev
        run: dart-lang/setup-dart/.github/workflows/publish.yml@v1
      - name: Publish
        run: dart pub publish -f
