
name: CI/CD
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
  pull_request: null
  release:
    types:
      - created
  workflow_dispatch: null
jobs:
  # THIS WORKS GOOD
  #pub-dry-run:
  #  name: Publish Dry Run
  #  runs-on: ubuntu-latest
  #  container: ghcr.io/cirruslabs/flutter:3.13.5
  #  timeout-minutes: 20
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
  #    - name: Run publish dry run
  #      run: flutter pub publish --dry-run

  #publish:
  #  permissions:
  #    id-token: write # Required for authentication using OIDC
  #  uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
  #  with:
  #    working-directory: franciscommcunha/flutter.ci.test/.github/workflows/publish.yml
  #
  release:
    name: Release
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.5
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: flutter pub get
      - name: Setup Pub Credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: .scripts/check_credentials.sh
      - name: Publish
        run: flutter pub publish -f
