
name: CI/CD
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      
    branches:
      - main
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  pub-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.5
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run publish dry run
        run: flutter pub publish --dry-run

  # THIS WORKS GOOD AND PUBLISHED WHEN A TAG IS CREATED AND PUSHED
  #publish:
  #  permissions:
  #    id-token: write # Required for authentication using OIDC
  #  uses: dart-lang/setup-dart/.github/workflows/publish.yml@main

  # THIS WORKS GOOD AND PUBLISHED WHEN A TAG IS CREATED AND PUSHED
  # but we need to add the write permission
  # and add - uses: dart-lang/setup-dart@v1 to the steps

  # https://birju.dev/posts/publish-your-flutter-package-using-github-actions/
  # https://dart.dev/tools/pub/automated-publishing
  release:
    name: Release
    permissions:
      id-token: write # Required for authentication using OIDC
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.5
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      #- uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        run: flutter pub get
      #- name: Setup Pub Credentials
      #  shell: bash
      #  env:
      #      PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #      PUB_DEV_PUBLISH_ID_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
      #      PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      #      PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
      #      PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      #  run: sh ./scripts/check_credentials.sh
      - name: Publish
        run: flutter pub publish -f
