
name: Publishing
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  pub-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.5
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run publish dry run
        run: flutter pub publish --dry-run

  # https://birju.dev/posts/publish-your-flutter-package-using-github-actions/
  # https://dart.dev/tools/pub/automated-publishing
  release:
    name: Release
    permissions:
      id-token: write # Required for authentication using OIDC
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.13.5
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set publishing token
        uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        run: flutter pub get
      - name: Publish
        run: flutter pub publish -f

# 9.0.0
# it seems to be working now, however not running the dry run because it is missing in the on.push
# works if creating a tag from terminal and publishes
#  -> but if does not create release on github
#  -> i go to github, create a release, the release fails because it already exists

# 10.0.0
# it seems to be working now, however not running the dry run because it is missing in the on.push
# works if creating a tag from github by creating a new release from there
# -> it will trigger tro actions, one that can publish and other fails because it says that it can not from release event
